version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" #Host port:Container port.  Remove in production for security.
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "dbname"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    ports:
      - "80:80"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 5s
      retries: 3
networks:
  mynetwork:

volumes:
  db_data:
